services:
  configdb1:
    image: mongo:latest
    command: mongod --configsvr --replSet cfgreplset --port 27017 --bind_ip 0.0.0.0
    ports:
      - "27017:27017"
    volumes:
      - configdb1-data:/data/db
    networks:
      - mongo-network

  configdb2:
    image: mongo:latest
    command: mongod --configsvr --replSet cfgreplset --port 27017 --bind_ip 0.0.0.0
    ports:
      - "27018:27017"
    volumes:
      - configdb2-data:/data/db
    networks:
      - mongo-network

  configdb3:
    image: mongo:latest
    command: mongod --configsvr --replSet cfgreplset --port 27017 --bind_ip 0.0.0.0
    ports:
      - "27019:27017"
    volumes:
      - configdb3-data:/data/db
    networks:
      - mongo-network

  shard1-repl1:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1 --port 27017 --bind_ip 0.0.0.0
    ports:
      - "27020:27017"
    volumes:
      - shard1-repl1-data:/data/db
    networks:
      - mongo-network

  shard1-repl2:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1 --port 27017 --bind_ip 0.0.0.0
    ports:
      - "27021:27017"
    volumes:
      - shard1-repl2-data:/data/db
    networks:
      - mongo-network

  shard1-repl3:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1 --port 27017 --bind_ip 0.0.0.0
    ports:
      - "27022:27017"
    volumes:
      - shard1-repl3-data:/data/db
    networks:
      - mongo-network

  mongos:
    image: mongo:latest
    command: mongos --configdb cfgreplset/configdb1:27017,configdb2:27017,configdb3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - "27023:27017"
    depends_on:
      - configdb1
      - configdb2
      - configdb3
      - shard1-repl1
      - shard1-repl2
      - shard1-repl3
    networks:
      - mongo-network

networks:
  mongo-network:

volumes:
  configdb1-data:
  configdb2-data:
  configdb3-data:
  shard1-repl1-data:
  shard1-repl2-data:
  shard1-repl3-data:
