services:
  # Конфигурационные серверы
  config1:
    image: mongo:latest
    container_name: config1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    volumes:
      - config1_data:/data/db

  config2:
    image: mongo:latest
    container_name: config2
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all"]
    networks:
      - mongo-cluster
    volumes:
      - config2_data:/data/db

  config3:
    image: mongo:latest
    container_name: config3
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all"]
    networks:
      - mongo-cluster
    volumes:
      - config3_data:/data/db

  # Шард (репликационный набор)
  shard1_1:
    image: mongo:latest
    container_name: shard1_1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--bind_ip_all"]
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    volumes:
      - shard1_1_data:/data/db

  shard1_2:
    image: mongo:latest
    container_name: shard1_2
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--bind_ip_all"]
    networks:
      - mongo-cluster
    volumes:
      - shard1_2_data:/data/db

  shard1_3:
    image: mongo:latest
    container_name: shard1_3
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--bind_ip_all"]
    networks:
      - mongo-cluster
    volumes:
      - shard1_3_data:/data/db

  # Mongos - маршрутизатор
  mongos:
    image: mongo:latest
    container_name: mongos
    command: ["mongos", "--configdb", "configReplSet/config1:27017,config2:27017,config3:27017", "--bind_ip_all"]
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster

# Определение сети
networks:
  mongo-cluster:

# Определение томов для хранения данных
volumes:
  config1_data:
  config2_data:
  config3_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
